[package]
name = "ntex-amqp"
version = "6.0.0-beta.0"
authors = ["ntex contributors <team@ntex.rs>"]
description = "AMQP 1.0 Client/Server framework"
documentation = "https://docs.rs/ntex-amqp"
repository = "https://github.com/ntex-rs/ntex-amqp.git"
categories = ["network-programming"]
keywords = ["AMQP", "IoT", "messaging"]
license = "MIT OR Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config"]
edition = "2024"
rust-version = "1.95"

[workspace]
members = [
  ".",
  "codec",
]

[workspace.lints.rust]
async_fn_in_trait =  { level = "allow", priority = -1 }
rust_2018_idioms = "deny"
warnings = "deny"
unreachable_pub = "deny"

[lints]
workspace = true

[features]
default = []

# log frames on trace level
frame-trace = []

[dependencies]
ntex-amqp-codec = "3.0.0-beta.0"

ntex-bytes = "1.9.0"
ntex-error = "2.5"
ntex-router = "1"
ntex-dispatcher = "4.0.0-beta.0"
ntex-io = "4.0.0-beta.0"
ntex-net = "4.0.0-beta.0"
ntex-util = "4.0.0-beta.2"
ntex-service = "5.0.0-beta.2"
ntex-rt = "3.17.1"

bitflags = "2"
derive_more = { version = "2", features = ["from"] }
log = "0.4"
pin-project-lite = "0.2"
slab = "0.4"
thiserror = "2"
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
ntex = "4.0.0-beta.0"
ntex-server = "4.0.0-beta.0"
ntex-amqp = { path = ".", features = ["frame-trace"] }

env_logger = "0.11"
rand = "0.9"

[patch.crates-io]
ntex-amqp = { path = "." }
ntex-amqp-codec = { path = "codec" }
